accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('mypage/', views.mypage, name='mypage')
]

characters/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
import os 
from . import views

app_name = 'characters'

urlpatterns = [
    path('index/', views.index, name='index'),
    # path('signup/', views.signup, name='signup'),
    path('list/', views.CharaList.as_view(), name='list'),
    path('chara/', views.chara, name='chara'),
    path('table/', views.CharaTable.as_view(), name='table'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
import os 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('characters/', include('characters.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from config import settings



#createsuperuser作成時のクラスのオーバーライド
class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        email = self.normalize_email(email)
        user = self.model(email=self.normalize_email(email),)
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
 
class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True,)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
 
    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
 
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, unique=True, on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(default="匿名ユーザー",max_length=30,)
    zipcode = models.CharField(default="郵便番号", max_length=8)
    prefecture = models.CharField(default="都道府県", max_length=5)
    city = models.CharField(default="市町村", max_length=100)
    address = models.CharField(default="建物名", max_length=200)

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return self.username

characters/models.py
from django.db import models


GENDER = (
    ('', '性別を選んでください'),
    ('unknown', 'unknown'),
    ('man', 'man'),
    ('woman', 'woman'),
)

class Characters(models.Model):
    name = models.CharField('名前', max_length=20)
    gender = models.CharField('性別',max_length=7, choices=GENDER)
    discription = models.CharField('特徴', max_length=1000)
    image = models.ImageField('写真', upload_to='media/', null=True)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password
 
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
        )

characters/forms.py
from django import forms
from .models import Characters
import django_filters

"""
class CharactersForm(forms.Form):
    name = forms.CharField(label='名前', max_length=20)
    gender = forms.ChoiceField(label='性別', widget=forms.RadioSelect,
        choices = (
            ('unknown', '不明'),
            ('man', '男'),
            ('woman', '女'),
        )
    )  
    discription = forms.CharField(label="説明", max_length=1000)
"""


class CharactersModelForm(forms.ModelForm):

    class Meta:
        model = Characters
        fields = ('name', 'gender', 'discription', 'image')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from .forms import UserCreationForm, ProfileForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from .models import Profile

class Login(LoginView):
    template_name = 'accounts/auth.html'

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self,form):
        return super().form_invalid(form)

class Logout(LogoutView):
    template_name = 'accounts/auth.html'

def signup(request):
    if request.method == 'POST':
        form_user = UserCreationForm(request.POST)
        if form_user.is_valid():
            user = form_user.save(commit=False)
            user.save()
            login(request, user)
            return redirect('/characters/index')
    return render(request, 'accounts/auth.html')

@login_required
def mypage(request):
    form = ProfileForm()


    if request.method == 'POST':
        form_profile = ProfileForm(request.POST)
        if form_profile.is_valid():
            profile = form_profile.save(commit=False)
            profile.user = request.user
            profile.save()
    return render(request, 'accounts/mypage.html', context={'form': form})

characters/views.py
from django.shortcuts import render
from .forms import CharactersModelForm
from django.views.generic import TemplateView, DetailView
from .models import Characters
from .tables import CharactersTable
from django_tables2 import SingleTableView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def index(request):
    return render(request, 'characters/index.html')
    
"""
def signup(request):
    form = CharactersForm()
    if request.method == 'POST':
        form = CharactersForm(request.POST)
        if form.is_valid():
            print('バリデーション成功')
            print(f"name: {form.cleaned_data['name']}, gender: {form.cleaned_data['gender']}, discription: {form.cleaned_data['discription']}")

    return render(request, 'characters/signup.html', context={'form': form})
"""

@login_required
def chara(request):
    form = CharactersModelForm()
    if request.method == 'POST':
        form = CharactersModelForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
        else:
            print('エラーがありました')
    return render(request, 'characters/form_model.html', context = {'form': form})

        


class CharaList(LoginRequiredMixin, TemplateView):
    model = Characters
    template_name = 'characters/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['characters'] = Characters.objects.all()
        return context

class CharaTable(LoginRequiredMixin, SingleTableView):
    table_class = CharactersTable
    template_name = 'characters/table.html'
    queryset = Characters.objects.all()

    def get_queryset(self):
        query = super().get_queryset()
        character_name = self.request.GET.get('name')
        character_gender = self.request.GET.get('gender')
        if character_name:
            query = query.filter(name=character_name)
            print(query, 'name')
            return query
        if character_gender:
            query = query.filter(gender=character_gender)
            print(query, 'gender')
            return query
        return query


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tables'] = Characters.objects.all()
        return context

templates/accounts/auth.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-3 m-auto ">
            <h1 class="display-4 fst-italic text-center "><a href="/" class="text-decoration-none">LeapsOnlineShop</a></h1>
        </div>
        <div class="col-lg-3 m-auto ">
            <form class="form-signin mx-4" method="POST">
                {% csrf_token %}
                
                <div class="text-center">
                    <h1 class="h5 my-4 ">
                        {% if 'login' in request.path %}
                        ログイン
                        {% elif 'signup' in request.path %}
                        新規登録
                        {% endif %}
                    </h1>
                </div>
 
                <div class="form-label-group my-3">
                    <input name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}" type="email" id="id_email" class="form-control" placeholder="Email address" required autofocus>
                </div>
 
                <div class="form-label-group my-3">
                    <input name="password" type="password" id="id_password" class="form-control" placeholder="Password" required>
                </div>
                <div class="form-label-group my-3 text-center">
                    <button class="btn btn-primary btn-block my-3" type="submit">サインイン</button>
                </div>
            </form>
 
            {% if 'login' in request.path %}
            <div class="text-center">
                <a href="{% url 'accounts:signup' %}" class="link-secondary">新規登録はこちら</a>
            </div>
            {% elif 'signup' in request.path %}
            <div class="text-center">
                <a href="{% url 'accounts:login' %}" class="link-secondary">ログインはこちら</a>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

templates/accounts/mypage.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if form %}
        {{ request.user.profile.username }}
        {{ request.user.profile.zipcode }}
        {{ request.user.profile.prefecture }}
        {{ request.user.profile.city }}
        {{ request.user.profile.address }}
    {% else %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    {% endif %}
    
</form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>django_practice</title>
  </head>
  <body>
    {% include 'header.html' %}
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

templates/characters/form_model.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="送信">
</form>

{% endblock%}

templates/characters/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/characters/list.html
{% extends 'base.html' %}
{% block content %}
{% for character in characters %}
{{ character.name }}
{{ character.gender }}
{{ character.discription }}
{% endfor %}
{% endblock %}

templates/characters/signup.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

templates/characters/table.html
{% extends 'base.html' %}
{% load render_table from django_tables2%}
{% load static %}
{% block content %}
<div class="container-fluid">
    <form action="{% url 'characters:table' %}" method="GET">
        <p>名前で検索: <input type="text" name="name"></p>
        <p>性別で検索: <input type="text" name="gender"></p>
        <p><input type="submit" value="検索"></p>
    </form>



    <!-- 水平方向の横スクロールバーを加える -->
    <div class="table-responsive col-auto">
        <!-- 縞ストライプで見やすくする -->
        <table class="table table-striped">
            {% if table %}
                {% render_table table %}
            {% endif %}
        </table>
    </div>
</div>
{% for table in tables %}
<img src="/media/{{table.image}}" alt="">

{% endfor %}

{% endblock %}

templates/header.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">鬼滅の刃</a>
    <ul class="dropdown-menu" aria-labelledby="dropdown03">
      <li><a class="dropdown-item" href="{% url 'characters:chara' %}">キャラクター登録</a></li>
      <li><a class="dropdown-item" href="{% url 'characters:table'  %}">キャラクター一覧</a></li>
    </ul>
    <ul>
      {% if user.is_authenticated %}
      <li>{{request.user|truncatechars_html:10}}さんがログイン中です</li>
      <li><a href="{% url 'accounts:mypage' %}">マイページ</a></li>
      <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
      {% endif %}
    </ul>
</li>